charts/tekton/Chart.yaml
charts/tekton/README.md

Simply bumped current 1.4.0 version to 1.5.0 because I had unresolvable issue with cached tekton on PGA cluster

feat: add 1.5.0 tag as bump of 1.4.0

---

.github/workflows/release.yml
charts/tekton-apps/Chart.yaml
charts/tekton-apps/README.md
charts/tekton-apps/templates/general/triggerbindings.yaml

this PR fixes double entry in the triggerbinding
kubernetes_branch is listed twice
an example of the values.yaml file
```yaml
environment: staging
gitBranchPrefixes:
- staging
- release
storageClassName: "gp2"
aws:
region: "us-east-2"
dns: proxylegalstaging.com
defaultRegistry: 833737135757.dkr.ecr.us-east-2.amazonaws.com
argocd:
server: deploy.proxylegalstaging.com
eventlistener:
enableWebhookSecret: true
apps:
- project: nmbl
enabled: true
argocd:
labels:
created-by: DmitrySemenov
ops-main: DmitrySemenov
ops-secondary: KseniyaShaydurova
pm: VadikKuznetsov
tm: AlekseyBashirov
namespace: staging
syncWave: 200
mailList: nmbl@saritasa.com
devopsMailList: devops+nmbl@saritasa.com
jiraURL: https://saritasa.atlassian.net/browse/NMBLCLD
tektonURL: …
```

fix: adjust triggerbinding generation template

---

charts/tekton-pipelines/Chart.yaml
charts/tekton-pipelines/values.yaml

Make dotnet pipeline use the same GitVersion version as we use in our GH actions for windows builds: https://github.com/saritasa-nest/ccf-ccl-backend/blob/develop/.github/workflows/windows-build.yml#L39
It seems, the current version doesn't always work with .NET 6 projects.

feat: update gitversion image for dotnet

---

charts/tekton-apps/Chart.yaml
charts/tekton-apps/README.md
charts/tekton-apps/templates/general/argocd_applications.yaml
charts/tekton-apps/values.yaml

Add possibility to ignore deployment replica sets differences in ArgoCD applications. It is needed for HPA in staging and prod K8S clusters.
Added new parameter to components:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
name: tekton-apps
namespace: argo-cd
finalizers:
- resources-finalizer.argocd.argoproj.io
annotations:
argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
argocd.argoproj.io/sync-wave: "41"
spec:
destination:
server: https://kubernetes.default.svc
namespace: ci
project: default
source:
chart: saritasa-tekton-apps
helm:
values: |
environment: staging
...
apps:
- project: xxx-dev
environment: dev
enabled: true
argocd:
labels:
created-by: xxx
ops-main: xxx
ops-secondary: xxx
pm: xxx
tm: xxx
namespace: xxx-dev
extraDestinationNamespaces:
- …
```

feat: add `ignoreDifference` for tekton-apps ArgoCD apps

---

charts/maintenance-page/.helmignore
charts/maintenance-page/Chart.yaml
charts/maintenance-page/README.md
charts/maintenance-page/README.md.gotmpl
charts/maintenance-page/templates/_helpers.tpl
charts/maintenance-page/templates/configmap.yaml
charts/maintenance-page/templates/deployment.yaml
charts/maintenance-page/templates/service.yaml
charts/maintenance-page/templates/serviceaccount.yaml
charts/maintenance-page/values.yaml

display maintenance page inside kubernetes cluster
uses this docker image: https://github.com/saritasa-nest/saritasa-devops-docker-images/pull/29
See it in action:
https://player.vimeo.com/video/736346976?h=1d7685f9d6&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479

feat: add kuberntest maintenance page helm chart

---

charts/tekton-apps/Chart.yaml
charts/tekton-apps/README.md
charts/tekton-apps/templates/wordpress/argocd_applications.yaml

I also updated values.yaml in rocks to include these versions for all WP components
```yaml
components: 
- name: wordpress
repository: augcard-wordpress
pipeline: wordpress-build-pipeline
applicationURL: https://augcard.saritasa.rocks
argocd:
source:
targetRevision: 15.0.16
wordpress:
imageTag: 6.0.1-debian-11-r12
resources:
```
updated wordpresses:
- https://bollards.saritasa.rocks/
- https://augcard.saritasa.rocks/
- https://haulink-wp.saritasa.rocks/
- https://blog.interesnee.saritasa.rocks/
- https://wordpress.demo.saritasa.rocks/
- https://taco.saritasa.rocks/
- https://webrefresh.technoir.saritasa.rocks/
- https://poc.zincasa.saritasa.rocks/
- https://webrefresh.technoir.saritasa.rocks/

feat: upgrade wordpress version

---

charts/tekton-apps/Chart.yaml
charts/tekton-apps/templates/general/triggerbindings.yaml
charts/tekton-pipelines/Chart.yaml
charts/tekton-pipelines/templates/_snippets.tpl
charts/tekton-pipelines/templates/buildpacks/pipelines/_buildpack.yaml
charts/tekton-pipelines/templates/buildpacks/trigger-templates/_buildpack.yaml
charts/tekton-pipelines/templates/kaniko/trigger-template.yaml
charts/tekton-pipelines/values.yaml

These changes are needed for `ovio` project .NET backend build - https://saritasa.atlassian.net/browse/OVIO-4
Currently it is deployed in `ci-experiments` namespace (with `tekton-apps-experiments` and `tekton-pipelines-experiments` charts)

feat: add `repository_submodules` flag to enable/disable loading submodules, add dotnet step to ignore `*.dcproj` files

---

charts/tekton-apps/Chart.yaml
charts/tekton-apps/README.md
charts/tekton-apps/templates/job.yaml
charts/tekton-apps/templates/wordpress/argocd_applications.yaml

- add ability to ignore replicas for wordpress components so we can downscale/freeze namespaces to free resouces
- add ability to run postinstall tekton apps job to mount pvc (to make argo app not progressing) on a specific node selector.

feat: add ingore replicas diff to wordpress components and nodeSelector for runPostInstallMountPvcJob

---

charts/tekton-pipelines/Chart.yaml
charts/tekton-pipelines/README.md
charts/tekton-pipelines/templates/common/tasks/kustomize.yaml
charts/tekton-pipelines/values.yaml

To mitigate problem, when `yamlfix` breaks deployment:
1. Use https://kubeval.instrumenta.dev/ which validates Kubernetes resources agaist JSON Schema for all Kubernetes resources (repository https://github.com/yannh/kubernetes-json-schema content is automatically generated from Kubernetes source code)
2. Apply Yamlfix only to overlay (`apps/{app}/manifests/{env}`), affected by `kustomize`, not whole `apps` folder (ex. we won't break production by commit to `develop` branch). Also, commit to frontend will not break backend and vice versa.

[tekton-pipelines] - new 'kubeval' step

---

.github/CODEOWNERS
charts/tekton-pipelines/Chart.yaml
charts/tekton-pipelines/README.md
charts/tekton-pipelines/templates/common/tasks/kustomize.yaml
charts/tekton-pipelines/values.yaml

deprecate `k8s.gcr.io` which was used by our tekton kustomize task
https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/
```
➜ k ice image -A G k8s.gcr.io                                   
ci                               ats-dart-backend-dev-kaniko-build-pipeline-run-cm5j8-kust-tvslh  step-update-image                      IfNotPresent  k8s.gcr.io/kustomize/kustomize                                                  v4.5.4
ci                               ats-dart-backend-dev-kaniko-build-pipeline-run-vzpw2-kust-sdgcm  step-update-image                      IfNotPresent  k8s.gcr.io/kustomize/kustomize                                                  v4.5.4
ci                               ats-dart-frontend-sales-dev-build-pipeline-run-z6mc9-kust-gwzlw  step-update-image …
```

[tekton-pipelines] - deprecate k8s.gcr.io repo

---

charts/tekton-apps/Chart.yaml
charts/tekton-apps/README.md
charts/tekton-apps/templates/wordpress/argocd_applications.yaml

Resolve secret provision for wp via tekton-apps.
If we provide `.existingSecret` with `.smtpPassword` helm creates secret without `wordpress-password` and reverts manual update for it. See logic here: https://github.com/bitnami/charts/blob/main/bitnami/wordpress/templates/secrets.yaml
Helm uses same logic for naming so that changes won't break already existed deployments. 
Example of failure: https://deploy.saritasa.rocks/applications/premierfoodsafety-wordpress-dev

fix: secret provisioning for wp

---

charts/tekton-pipelines/Chart.yaml
charts/tekton-pipelines/README.md
charts/tekton-pipelines/values.yaml

Disable hashes for poetry requirements export
Resolves issue with dependecies in git repos, like this:
```
ERROR: Can't verify hashes for these requirements because we don't have a way to hash version control repositories:
django-s3direct@ git+https://github.com/Saritasa/django-s3direct.git@6bc6d843b64da8e399b29caed211fccd6e9961a0 from git+https://github.com/Saritasa/django-s3direct.git@6bc6d843b64da8e399b29caed211fccd6e9961a0 (from -r requirements.txt (line 170))
pip install failed:
error: exit status 1
ERROR: failed to build: exit status 1
Step failed
```
Task: https://saritasa.atlassian.net/browse/JC-560

fix: disable hashes for poetry export

---

charts/tekton-apps/Chart.yaml
charts/tekton-apps/README.md
charts/tekton-apps/templates/wordpress/argocd_applications.yaml

PHP node is overloaded. By defautl bitnami helmchart performs liveness/readness healthchecks every 10 seconds (ping to `GET /wp-admin/install.php` which is non-trivial check). 
So by default each WP project consumes arount 5% CPU (~50m) only for healthcecks.
With mutiple WP projects running less frequenet liveness/readness probes execution allows to reduce CPU consumption significantly.

feat: less frequent healthchecks for WordPress

---

charts/tekton-apps/Chart.yaml
charts/tekton-apps/README.md
charts/tekton-apps/values-test.yaml

[TASK](https://saritasa.atlassian.net/browse/SD-556)
Related to https://github.com/saritasa-nest/saritasa-rocks-kubernetes-aws/pull/209 and https://github.com/saritasa-nest/saritasa-devops-boilerplates/pull/149
Added a webhook integration for argocd notifications
For rocks/cloud cluster keep adding notifications in tekton-apps AppProject as:
```yaml
notifications:
annotations:
notifications.argoproj.io/subscribe.on-health-degraded.slack: camp-python-2023; camp-python-2023-alarms
notifications.argoproj.io/subscribe.on-sync-failed.slack: camp-python-2023-ci; camp-python-2023-alarms
notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: camp-python-2023; camp-python-2023-alarms
notifications.argoproj.io/subscribe.on-deployed.slack: camp-python-2023-ci; camp-python-2023-alarms
``` …

feat: add ArgoCD webhook integration

---

.github/mergeable.yml
CHANGELOG.md

jira: https://saritasa.atlassian.net/browse/SD-717
Mergeable automates GitHub workflow
You can configure it in the .github repository, in the file .github/mergeable.yml
We use the [following recipes](https://github.com/saritasa-nest/saritasa-devops-helm-charts/blob/feature/add-github-bot-mergeable/.github/mergeable.yml)
Descriptions of all configuration blocks can be found [here](https://github.com/saritasa-nest/saritasa-rocks-kubernetes-aws/pull/239)

feat: adding configuration for saritasa-mergeable application

---

CHANGELOG.md
charts/grafana-dashboards/.helmignore
charts/grafana-dashboards/Chart.yaml
charts/grafana-dashboards/README.md
charts/grafana-dashboards/README.md.gotmpl
charts/grafana-dashboards/templates/ingress-nginx/controller-loki.yaml
charts/grafana-dashboards/templates/ingress-nginx/controller.yaml
charts/grafana-dashboards/templates/ingress-nginx/request-handling-performance.yaml
charts/grafana-dashboards/values.yaml

JIRA: <https://saritasa.atlassian.net/browse/USAWS-23>
Added `grafana-dashboards` helm chart (only dashboard for ingress-nginx).
[ingress-nginx dashboards](https://grafana.teleport.usummitapp.net/dashboards/f/b2e50ac0-8808-42da-a530-cd0563f1dc76/)
Related PR: <https://github.com/saritasa-nest/usummit-kubernetes-aws/pull/9>

feat: add `grafana-dashboards` helm chart

---

CHANGELOG.md
charts/grafana-dashboards/Chart.yaml
charts/grafana-dashboards/README.md
charts/grafana-dashboards/templates/cicd/argocd.yaml
charts/grafana-dashboards/templates/databases/mysql.yaml
charts/grafana-dashboards/templates/databases/postgresql.yaml
charts/grafana-dashboards/templates/istio/control-plane.yaml
charts/grafana-dashboards/templates/istio/mesh.yaml
charts/grafana-dashboards/templates/istio/performance.yaml
charts/grafana-dashboards/templates/istio/service.yaml
charts/grafana-dashboards/templates/istio/wasm-extension.yaml
charts/grafana-dashboards/templates/istio/workload.yaml
charts/grafana-dashboards/values.yaml

JIRA: <https://saritasa.atlassian.net/browse/USAWS-23>
Added `cicd`, `databases`, `istio` dashboards in `grafana-dashboards`helm chart
[cicd dashboards](https://grafana.teleport.usummitapp.net/dashboards/f/e699caf7-76b0-4c5b-af95-25f622adcbe9/cicd)
[databases dashboards](https://grafana.teleport.usummitapp.net/dashboards/f/beb18cb5-9a6c-4a23-bbfa-0568075ac2bf/)
[istio dashboards](https://grafana.teleport.usummitapp.net/dashboards/f/c56ef086-a874-492e-8208-b9a8872e56f3/)
Related PR: https://github.com/saritasa-nest/usummit-kubernetes-aws/pull/12

feat: add dashboards in `grafana-dashboards` helm chart

---

CHANGELOG.md
charts/grafana-dashboards/Chart.yaml
charts/grafana-dashboards/README.md
charts/grafana-dashboards/templates/alerts/alertmanager.yaml
charts/grafana-dashboards/templates/default/generic-service-metrics.yaml
charts/grafana-dashboards/templates/default/home.yaml
charts/grafana-dashboards/templates/knative/eventing-broker-trigger.yaml
charts/grafana-dashboards/templates/knative/eventing-source.yaml
charts/grafana-dashboards/templates/knative/reconciler.yaml
charts/grafana-dashboards/templates/knative/serving-control-plane-efficiency.yaml
charts/grafana-dashboards/templates/knative/serving-revision-cpu-memory-usage.yaml
charts/grafana-dashboards/templates/knative/serving-revision-http-requests.yaml
charts/grafana-dashboards/templates/knative/serving-scaling-debugging.yaml
charts/grafana-dashboards/templates/kubernetes/cluster-monitoring.yaml
charts/grafana-dashboards/templates/kubernetes/cluster-overall.yaml
charts/grafana-dashboards/templates/kubernetes/cluster-overview.yaml
charts/grafana-dashboards/templates/kubernetes/node-exporter-full.yaml
charts/grafana-dashboards/values.yaml

JIRA: <https://saritasa.atlassian.net/browse/USAWS-23>
Added `alerts`, `default`, `knative`, `kubernetes` dashboards in `grafana-dashboards`helm chart
- [alerts dashboards](https://grafana.teleport.usummitapp.net/dashboards/f/f46eb5c5-9b59-437b-979c-0e1bfb9ab2f4/)
- default dashboards:
- [home](https://grafana.teleport.usummitapp.net/d/sSAXTzv7z/home?orgId=1&refresh=5m)
- [generic service metrics](https://grafana.teleport.usummitapp.net/d/qqsCbY5Zz/generic-service-metrics?orgId=1&refresh=10s)
- [knative dashboards](https://grafana.teleport.usummitapp.net/dashboards/f/d9fc7a69-0ad1-469a-995a-79818180a89e/)
- [kubernetes dashboards](https://grafana.teleport.usummitapp.net/dashboards/f/fdf541bb-ce0c-461d-b453-7d130e26f57f/)
Related PR: …

feat: add new dashboards in grafana-dashboards chart

---

CHANGELOG.md
charts/tekton-apps/Chart.yaml
charts/tekton-apps/README.md
charts/tekton-apps/templates/roles.yaml

Suddenly our Tekton stopped sending Slack notifications for all projects with this error, so I found bug that appeared from this PR - https://github.com/saritasa-nest/saritasa-devops-helm-charts/pull/98/files (we should have `build-pipeline-role` roles in `ci` namespace by default).
Original Error: 
```
Error from server (Forbidden): [pipelineruns.tekton.dev](http://pipelineruns.tekton.dev/) "ats-dart-backend-dev-kaniko-build-pipeline-run-vv6cp" is forbidden: User "system:serviceaccount:ci:ats-dart-backend-dev-build-pipeline-sa" cannot get resource "pipelineruns" in API group "[tekton.dev](http://tekton.dev/)" in the namespace "ci": RBAC: [role.rbac.authorization.k8s.io](http://role.rbac.authorization.k8s.io/) …
```

feat: fix typo in tekton-apps roles creation

---

CHANGELOG.md
charts/terraform-pod/Chart.yaml
charts/terraform-pod/README.md
charts/terraform-pod/values.yaml

Task: [PEGGS-3](https://saritasa.atlassian.net/browse/PEGGS-3)
Release terraform with `1.8.3` version
[PEGGS-3]: https://saritasa.atlassian.net/browse/PEGGS-3?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: release terraform 1.8.3

---

CHANGELOG.md
charts/tekton-apps/Chart.yaml
charts/tekton-apps/templates/wordpress/argocd_applications.yaml

Task: [SD-1004](https://saritasa.atlassian.net/browse/SD-1004)
- Changed strategy type to `Recreate`
With the `RollingUpdate` strategy type we get an error:
```
Multi-Attach error for volume "pvc-007567f3-a6fd-498e-9fc7-f2cbf4d46631" Volume is already used by pod(s) emapp-wordpress-dev-56dfdd6d97-2dbt7
```
[SD-1004]: https://saritasa.atlassian.net/browse/SD-1004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: edit updateStrategy

---

CHANGELOG.md
charts/tekton-apps/Chart.yaml
charts/tekton-apps/templates/wordpress/argocd_applications.yaml

Task: [SD-1004](https://saritasa.atlassian.net/browse/SD-1004)
- update path for `readinessProbe` and `customLivenessProbe`
Even though the page  [wp-login.php](https://saritasa-ci-experiments-wordpress.saritasa.rocks/wp-login.php) is in pod, we can't use it for  `readinessProbe` and `customLivenessProbe` because it must be in the `wp-content` folder in all `wordpress` repositories.
[SD-1004]: https://saritasa.atlassian.net/browse/SD-1004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: update path for readinessProbe and customLivenessProbe

---

CHANGELOG.md
charts/terraform-pod/Chart.yaml
charts/terraform-pod/README.md
charts/terraform-pod/values.yaml

JIRA: [SD-373](https://saritasa.atlassian.net/browse/SD-373)
Changes:
* release a Helm chart for terraform-pod with terraform version 1.11.3 (uses [new `base` image](https://github.com/saritasa-nest/saritasa-devops-docker-images/pull/101))

feat: release terraform-pod 1.11.3

---

CHANGELOG.md
charts/tekton-apps/Chart.yaml
charts/tekton-apps/README.md
charts/tekton-pipelines/Chart.lock
charts/tekton-pipelines/Chart.yaml
charts/tekton-pipelines/README.md
charts/tekton-pipelines/TODO
charts/tekton-pipelines/templates/_snippets.tpl
charts/tekton-pipelines/templates/buildpacks/pipelines/_buildpack.yaml
charts/tekton-pipelines/templates/buildpacks/tasks/_buildpack.yaml
charts/tekton-pipelines/templates/buildpacks/tasks/prepare-buildpack-build.yaml
charts/tekton-pipelines/templates/buildpacks/trigger-templates/_buildpack.yaml
charts/tekton-pipelines/templates/common/tasks/_pre-deploy.yaml
charts/tekton-pipelines/templates/common/tasks/detect-nodejs-version.yaml
charts/tekton-pipelines/templates/common/tasks/git-clone-catalog.yaml
charts/tekton-pipelines/templates/common/tasks/git-clone.yaml
charts/tekton-pipelines/templates/common/tasks/kustomize.yaml
charts/tekton-pipelines/templates/common/tasks/sentry-release.yaml
charts/tekton-pipelines/templates/common/triggers/github-trigger-binding.yaml
charts/tekton-pipelines/templates/kaniko/pipeline.yaml
charts/tekton-pipelines/templates/kaniko/tasks/kaniko.yaml
charts/tekton-pipelines/templates/kaniko/trigger-template.yaml
charts/tekton-pipelines/templates/wordpress/trigger-template.yaml
charts/tekton-pipelines/values.yaml
charts/tekton/README.md

Task: [SD-1271](https://saritasa.atlassian.net/browse/SD-1271)
- Update tekton-pipelines:
- Removed resources blocks as they are deprecated
- Add new git-clone task from tekton catalog
- update all pipelines to use new versions and tasks
We previously used resources block to git clone the backend/frontend and also to clone the xx-kubernetes-repo.
I have added two new tasks to all pipelines
```
- git-clone-catalog
- git-clone-kubernetes
```
This run as the 1st step to replace the `resources`.
Charts were installed and tested in rma-staging and aaoa-ari-staging
Dotnet pipeline:
<details>
https://tekton.staging.dispatch.rmacompanies.com/#/pipelineruns
</details>
Kaniko and wordpress pipeline:
<details>
https://tekton.staging.tenantalert.com/#/pipelineruns
</details>
Related PRs:
- …

feat: release tekton pipelines 2.0 SD-1271

---

CHANGELOG.md
charts/tekton-pipelines/Chart.yaml
charts/tekton-pipelines/README.md
charts/tekton-pipelines/templates/buildpacks/pipelines/_buildpack.yaml
charts/tekton-pipelines/templates/buildpacks/tasks/_buildpack.yaml
charts/tekton-pipelines/templates/buildpacks/trigger-templates/_buildpack.yaml
charts/tekton-pipelines/values.yaml

Task: [SD-1342](https://saritasa.atlassian.net/browse/SD-1342)
- added `set-env-vars` step to `buildpack-django` pipeline to set environment variables for buildpack-django
- removed `requirements.txt` creation with `poetry.lock` from `copy-requirements` step since `requirements.txt` file is not needed when specifying groups of packages to install via `BP_POETRY_INSTALL_ONLY` variable
[test pipelinerun](https://tekton.saritasa.rocks/#/namespaces/ci-experiments/pipelineruns/saritasa-ci-experiments-django-backend-dev-build-pipeline-qphrv?pipelineTask=buildpack-django&step=build)
variable set:
variable used in buildpack (default value is `main`):
passing additional environment variables:
```bash
triggerBinding:
- name: buildpack_env_vars
value: …
```

feat: add set-env-vars step for python buildpack SD-1342

---

CHANGELOG.md
charts/tekton-pipelines/Chart.yaml
charts/tekton-pipelines/README.md
charts/tekton-pipelines/templates/_snippets.tpl
charts/tekton-pipelines/templates/buildpacks/pipelines/_buildpack.yaml
charts/tekton-pipelines/templates/common/tasks/sentry-release.yaml
charts/tekton-pipelines/values.yaml

- add new git-clone-sentry step when pipeline is dotnet
Problem:
Dotnet pipelines were failing because the sentry step always resulted in failure:
Example: https://tekton.saritasa.rocks/#/namespaces/ci/pipelineruns/renewaire-backend-dev-build-pipeline-run-pw4kr?pipelineTask=sentry-release&step=release
The problem is that dotnet buildpack deletes the source code 
and then sentry can't evaluate the `VERSION` because there isn't a .git folder anymore.
Fix:
I have a conditional step git-clone-sentry that will only execute when the pipeline is dotnet
For all other buildpacks/kaniko the workflow is not modified
<details>
<summary>Proofs:</summary>
New step clones into sentry/ folder …

feat: add git-clone step to sentry SD-373

---

CHANGELOG.md
charts/tekton-apps/Chart.yaml
charts/tekton-apps/README.md
charts/tekton-apps/templates/wordpress/argocd_applications.yaml

Changes:
- specify `global.security.allowInsecureImages` for WordPress application to allow `bitnamilegacy` images
Without that option, I was getting this error on sync in Rocks:

feat: allow insecure WordPess images
