saritasa-nest/saritasa-devops-helm-charts

charts/tekton-pipelines/Chart.yaml, charts/tekton-pipelines/README.md, charts/tekton-pipelines/templates/common/tasks/kustomize.yaml
Updated tekton kustomize task for proper simultaneous access to k8s repo.
Applied and tested on rocks cluster.
=> feat: fixed git push loop in tekton kustomize task

charts/tekton-pipelines/Chart.yaml, charts/tekton-pipelines/README.md, charts/tekton-pipelines/values.yaml
Because of missing priorities task was exiting with 1 return code even in case of successfull build
=> Fix buildpack-frontend task failing

charts/rbac/Chart.yaml, charts/rbac/README.md, charts/rbac/templates/client/apps.yaml, charts/rbac/templates/client/ci.yaml, charts/rbac/templates/client/cluster.yaml, charts/rbac/templates/client/mongodb.yaml, charts/rbac/templates/client/mssql.yaml, charts/rbac/templates/client/postgres.yaml, charts/rbac/templates/developers/apps.yaml, charts/rbac/templates/developers/mongodb.yaml, charts/rbac/templates/developers/mssql.yaml, charts/rbac/templates/developers/mysql.yaml, charts/rbac/templates/developers/postgres.yaml, charts/rbac/templates/devops/cluster.yaml, charts/rbac/values.yaml
Add `devops-jr` rbac permissions + add rbac perms for `mongodb` and `mssql` namespaces
=> feat: extend `rbac` module with more permissions

charts/tekton-apps/Chart.yaml, charts/tekton-apps/README.md, charts/tekton-apps/templates/argocd_projects.yaml, charts/tekton-apps/templates/configmap.yaml, charts/tekton-apps/templates/eventlistener.yaml, charts/tekton-apps/templates/general/argocd_applications.yaml, charts/tekton-apps/templates/general/pvc.yaml, charts/tekton-apps/templates/general/serviceaccounts.yaml, charts/tekton-apps/templates/general/triggerbindings.yaml, charts/tekton-apps/templates/job.yaml, charts/tekton-apps/templates/roles.yaml, charts/tekton-apps/templates/serviceaccounts.yaml, charts/tekton-apps/templates/wordpress/argocd_applications.yaml, charts/tekton-apps/templates/wordpress/roles.yaml, charts/tekton-apps/templates/wordpress/serviceaccounts.yaml, charts/tekton-apps/templates/wordpress/triggerbindings.yaml
Fixed comments in `tekton-apps` according to Slack vote
=> feat: update comments for tekton-apps helm chart

charts/tekton-pipelines/Chart.yaml, charts/tekton-pipelines/README.md, charts/tekton-pipelines/values.yaml
upgrade node:14 -> node:16 based on this request from the frontend team: https://saritasa.atlassian.net/browse/FT-26
=> feat: add node:16 for nodejs static build steps

charts/tekton/Chart.yaml, charts/tekton/README.md, charts/tekton/templates/tekton-triggers.yaml
add ability to define nodeSelector/affinity for tekton-triggers-controller pod (which turned down to be on spot nodegroup in CCF project)
=> feat: add nodeSelector/affinity to tekton-triggers-controller

charts/tekton-apps/Chart.yaml, charts/tekton-apps/README.md, charts/tekton-apps/templates/eventlistener.yaml, charts/tekton-apps/values.yaml
add nodeSelector for pod created by event listener CRD
https://tekton.dev/vault/triggers-v0.11.2/eventlisteners/#resources
don't pay attention to tekton-pipelines changes as they're not merged into main yet from the previous PR I branched this off.
so only see the changes in tekton-apps
=> feat: add eventlistener node selector

.pre-commit-config.yaml, .pre-commit-hooks.yaml, README.md
- add proper README.md
- update pre-commit configs (updated to newer versions)
=> feat: update README.md

charts/rbac/Chart.yaml, charts/rbac/README.md, charts/rbac/templates/client/apps.yaml, charts/rbac/templates/developers/apps.yaml
needed so we (or the client) can perform
```
kubectl -n prod rollout restart deployment prod-backend-v1
```
=> feat: add rbac rollout deployment restart permission

charts/tekton-pipelines/Chart.yaml, charts/tekton-pipelines/README.md, charts/tekton-pipelines/values.yaml
address this error
https://tekton.saritasa.rocks/#/namespaces/ci/pipelineruns/invoke-backend-dev-build-pipeline-run-l699w?pipelineTask=buildpack-dotnet&step=get-semantic-version
=> feat: add git fetch unshallow

charts/tekton-apps/Chart.yaml, charts/tekton-apps/README.md, charts/tekton-apps/templates/general/argocd_applications.yaml, charts/tekton-apps/templates/general/argocd_extra_applications.yaml
used it first time for nmbl extra apps
https://github.com/saritasa-nest/saritasa-rocks-kubernetes-aws/pull/66
and [nmbl-kubernetes-aws](https://github.com/saritasa-nest/nmbl-kubernetes-aws/pull/11/commits/ea22297c891558d641d66891a4d84b567d4124b1)
=> feat: add ability to define extraApps through gitops

.github/workflows/test.yml, charts/tekton-pipelines/Chart.yaml, charts/tekton-pipelines/values.yaml
Adding ability to copy the Procfile file so that it can be used when building frontend app
https://github.com/paketo-buildpacks/procfile
=> [tekton-pipelines] - add Procfile for frontend build pipeline

charts/terraform-pod/Chart.yaml, charts/terraform-pod/values.yaml
- Added latest version of terraform 1.4.4
- Added nodeSelector for tfpod
=> feat: add terraform 1.4.4

charts/terraform-pod/Chart.yaml
- Added latest version of terraform 1.4.4
- Added nodeSelector for tfpod
PR without changes, to change the release tag from 0.0.9-dev.1 to 0.0.9
=> feat: update tag of release

charts/tekton-apps/Chart.yaml, charts/tekton-apps/README.md, charts/tekton-apps/values-test.yaml
Related to: https://github.com/saritasa-nest/saritasa-rocks-kubernetes-aws/pull/188
[Jira task](https://saritasa.atlassian.net/browse/SD-556)
Updated tekton-apps Readme and values-test.yml to current default values
(Didn't update the tekton-apps Chart version because this didn't change anything, just docs)
=> feat: update documentation for default argo-cd notificatitons

charts/terraform-pod/Chart.yaml, charts/terraform-pod/README.md, charts/terraform-pod/values.yaml
Release `terraform-pod` with 1.5.6 terraform version
=> feat: release terraform 1.5.6

.github/CODEOWNERS, charts/terraform-pod/Chart.yaml, charts/terraform-pod/README.md, charts/terraform-pod/values.yaml
Release terraform-pod with 1.5.7 terraform version
=> feat: release terraform 1.5.7

charts/terraform-pod/Chart.yaml, charts/terraform-pod/values.yaml
[JIRA DELMAR-64](https://saritasa.atlassian.net/browse/DELMAR-64)
- Added getting a secret to work with the saritasa-rocks-mssql instance
Next, the secret can be used together with the [provider](https://registry.terraform.io/providers/saritasa-nest/mssql/0.0.4) to create databases on the  saritasa-rocks-mssql instance
Tested in this [PR](https://github.com/saritasa-nest/saritasa-crm-delmar-infra-dev-aws/pull/3)
=> feat: add-mssql-creds

charts/terraform-pod/Chart.yaml, charts/terraform-pod/README.md, charts/terraform-pod/values.yaml
[JIRA SD-373](https://saritasa.atlassian.net/browse/SD-373)
Release terraform-pod with 1.6.1 terraform version
=> feat: new-version-of-terraform

charts/terraform-pod/Chart.yaml, charts/terraform-pod/README.md, charts/terraform-pod/values.yaml
Release terraform-pod with 1.6.2 terraform version
=> feat: release terraform 1.6.2

charts/tekton-apps/Chart.yaml, charts/tekton-apps/templates/wordpress/argocd_applications.yaml, charts/tekton-apps/values.yaml
Task [SD-373](https://saritasa.atlassian.net/browse/SD-373)
This string first checks the component.argocd.namespace field, if it does not exist - taking value from project.argocd.namespace
=> feat: updated the namespace selection method for wp chart

CHANGELOG.md, charts/terraform-pod/Chart.yaml, charts/terraform-pod/README.md, charts/terraform-pod/values.yaml
jira: https://saritasa.atlassian.net/browse/SD-373
Release terraform-pod with 1.6.6 terraform version
=> feat: release terraform 1.6.6

CHANGELOG.md, charts/terraform-pod/Chart.yaml, charts/terraform-pod/README.md, charts/terraform-pod/values.yaml
[JIRA SD-373](https://saritasa.atlassian.net/browse/SD-373)
Release terraform-pod with 1.7.0 terraform version
=> feat: add-terraform-1.7.0

CHANGELOG.md, charts/tekton-pipelines/Chart.yaml, charts/tekton-pipelines/README.md, charts/tekton-pipelines/templates/buildpacks/pipelines/_buildpack.yaml, charts/tekton-pipelines/templates/buildpacks/tasks/_buildpack.yaml, charts/tekton-pipelines/templates/buildpacks/trigger-templates/_buildpack.yaml, charts/terraform-pod/README.md
Update tekton-pipelines params for new jammy paketo buildpack usage
Task: https://saritasa.atlassian.net/browse/TEENCT-463
=> feat: tekton pipelines 0.1.44

CHANGELOG.md, charts/terraform-pod/Chart.yaml, charts/terraform-pod/README.md, charts/terraform-pod/values.yaml
Release new `terraform-pod` helm chart with `1.7.4` version
Task: https://saritasa.atlassian.net/browse/DART-1193
=> feat: release 1.7.4 terraform version for `terraform-pod` helm chart

.github/mergeable.yml, CHANGELOG.md
Task: [SD-717](https://saritasa.atlassian.net/browse/SD-717)
- add mergeable.yml 
Related PR: [#114](https://github.com/saritasa-nest/saritasa-devops-helm-charts/pull/114)
[SD-717]: https://saritasa.atlassian.net/browse/SD-717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add mergeable

CHANGELOG.md, charts/tekton-pipelines/Chart.yaml, charts/tekton-pipelines/README.md, charts/tekton-pipelines/templates/kaniko/tasks/kaniko.yaml
Fix typo for kaniko image params
Same as https://github.com/saritasa-nest/saritasa-devops-helm-charts/pull/103
Task: https://saritasa.atlassian.net/browse/SD-145
=> feat: fix typo in kaniko image variable

CHANGELOG.md, charts/tekton-pipelines/Chart.yaml, charts/tekton-pipelines/README.md, charts/tekton-pipelines/values.yaml
Task: [SD-902](https://saritasa.atlassian.net/browse/SD-902)
- Updated poetry version in tekton-pipelines: `1.5.1` -> `1.8.2`
Related PRs:
- https://github.com/saritasa-nest/saritasa-rocks-kubernetes-aws/pull/299
- https://github.com/saritasa-nest/saritasa-devops-docker-images/pull/70
[SD-902]: https://saritasa.atlassian.net/browse/SD-902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: updated-poetry

CHANGELOG.md, charts/terraform-pod/Chart.yaml, charts/terraform-pod/README.md, charts/terraform-pod/values.yaml
Task: [HURVR-5](https://saritasa.atlassian.net/browse/HURVR-5)
Release terraform with `1.8.5` version
[HURVR-5]: https://saritasa.atlassian.net/browse/HURVR-5?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: release terraform 1.8.5

CHANGELOG.md, charts/terraform-pod/Chart.yaml, charts/terraform-pod/README.md, charts/terraform-pod/values.yaml
Task: [SD-986](https://saritasa.atlassian.net/browse/SD-986)
Release terraform with `1.9.1` version
[SD-986]: https://saritasa.atlassian.net/browse/SD-986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: release terraform 1.9.1

CHANGELOG.md, charts/terraform-pod/Chart.yaml, charts/terraform-pod/README.md, charts/terraform-pod/values.yaml
Task: [IRW-101](https://saritasa.atlassian.net/browse/IRW-101)
Release terraform with 1.9.5 version
[IRW-101]: https://saritasa.atlassian.net/browse/IRW-101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: release terraform 1.9.5

CHANGELOG.md, charts/grafana-dashboards/Chart.yaml, charts/grafana-dashboards/README.md, charts/grafana-dashboards/templates/kubernetes/event-exporter.yaml, charts/grafana-dashboards/values.yaml
JIRA: <https://saritasa.atlassian.net/browse/USAWS-110>
Add `Kubernetes Event Exporter` dashboard to `grafana-dashboards` helm chart
[Kubernetes Event Exporter](https://grafana.teleport.usummitapp.net/d/kubernetes-event-exporter/kubernetes-event-exporter?orgId=1&refresh=1m)
=> feat: add kubernetes event exporter dashboard

CHANGELOG.md, charts/grafana-dashboards/Chart.yaml, charts/grafana-dashboards/README.md, charts/grafana-dashboards/templates/default/home.yaml
JIRA: [USAWS-113](https://saritasa.atlassian.net/browse/USAWS-113)
Update Home grafana dashboard
<https://grafana.teleport.usummitapp.net/d/sSAXTzv7z/home?orgId=1&refresh=1m>
[USAWS-113]: https://saritasa.atlassian.net/browse/USAWS-113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: edit home dashboard

CHANGELOG.md, charts/rbac/Chart.yaml, charts/rbac/README.md, charts/rbac/templates/client/apps.yaml, charts/rbac/templates/developers/apps.yaml, charts/rbac/values.yaml
developer role had resource names instead of verbs.
Enumerate resoures and verbs explicitly.
=> fix: RBAC roles had invalid definition

CHANGELOG.md, charts/terraform-pod/Chart.yaml, charts/terraform-pod/README.md, charts/terraform-pod/values.yaml
JIRA: [SD-1071](https://saritasa.atlassian.net/browse/SD-1071)
release helm chart `terraform-pod` with terraform version `1.9.7`
[SD-1071]: https://saritasa.atlassian.net/browse/SD-1071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: release terraform 1.9.7

CHANGELOG.md, charts/tekton-apps/Chart.yaml, charts/tekton-apps/README.md, charts/tekton-apps/templates/wordpress/argocd_applications.yaml, charts/tekton-apps/values-test.yaml
Task: [SCISM-3](https://saritasa.atlassian.net/browse/SCISM-3)
- enable the option to add priorityClass into Wordpress Helm chart 
Release: `tekton-apps:1.1.2`
Related PR: https://github.com/saritasa-nest/scripta-infra-aws/pull/11
[SCISM-3]: https://saritasa.atlassian.net/browse/SCISM-3?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add priorityClass for wordpress

CHANGELOG.md, charts/eol-exporter/Chart.yaml, charts/eol-exporter/README.md, charts/eol-exporter/values.yaml
Task: [SD-1098](https://saritasa.atlassian.net/browse/SD-1098)
Release new version to add the changes defined in https://github.com/saritasa-nest/saritasa-devops-tools-eol-exporter/pull/3
New tag: `eol-prometheus-exporter:0.1.1`
[SD-1098]: https://saritasa.atlassian.net/browse/SD-1098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: release new EOL version

CHANGELOG.md, charts/terraform-pod/Chart.yaml, charts/terraform-pod/README.md, charts/terraform-pod/values.yaml
JIRA: [SD-373](https://saritasa.atlassian.net/browse/SD-373)
release helm chart `terraform-pod` with terraform version `1.10.5`
=> feat: release terraform-pod 1.10.5

CHANGELOG.md, charts/terraform-pod/Chart.yaml, charts/terraform-pod/README.md, charts/terraform-pod/values.yaml
JIRA: [SD-373](https://saritasa.atlassian.net/browse/SD-373)
Changes:
* release a Helm chart for terraform-pod with terraform version 1.11.2
=> feat: release terraform-pod 1.11.2

.github/CODEOWNERS, .github/pull_request_template.md, .github/settings.yaml, CHANGELOG.md, charts/tekton-pipelines/Chart.yaml, charts/tekton-pipelines/README.md, charts/tekton-pipelines/values.yaml
- update poetry image with new one with UV support
- update `copy-requirements` task to support `uv.lock` files
<details>
<summary>Task output:</summary>
https://tekton.saritasa.rocks/#/namespaces/ci/pipelineruns/saritasa-devops-tools-github-promexporter-prod-build-pipeljqr55?pipelineTask=buildpack-django&step=copy-requirements&view=logs
</details>
Docker PR: https://github.com/saritasa-nest/saritasa-devops-helm-charts/pull/152
https://github.com/saritasa-nest/saritasa-devops-tools-github-promexporter/pull/3
=> feat: add uv.lock support for tekton-pipelines SD-373

CHANGELOG.md, charts/tekton-pipelines/Chart.yaml, charts/tekton-pipelines/README.md, charts/tekton-pipelines/templates/common/tasks/kustomize.yaml, charts/tekton-pipelines/values.yaml
Task: [SD-1355](https://saritasa.atlassian.net/browse/SD-1355)
- update `update-image` step to use yq, instead of kustomize edit
- update `yamlfix` step to use `.yamlfix.values.toml` as config 
Our `kustomize` task was using `kustomize edit set image` for updating the image in the `update-image` step. This was causing the lines inside of the kustomization.yaml files to be re-ordered in an inconvenient way (see this [commit made by tekton-kustomize in sportsthread-kubernetes-aws](https://github.com/saritasa-nest/sportsthread-kubernetes-aws/commit/4b3194e4003c0096c2a8cfd883ca03c63c423c64)):
This is a known issue in `kustomize edit` that is still unresolved:
- https://github.com/kubernetes-sigs/kustomize/issues/2310
- https://github.com/kubernetes-sigs/kustomize/issues/4481
So it was decided …
=> feat: update kustomize steps for yamlfix SD-1355
